// react-native-bullet-train/example/App.js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Button,
    Text,
    View
} from 'react-native';
import bulletTrain from "./bullet-train";

const environmentID = "QjgYur4LQTwe5HpvbvhpzK";

export default class App extends Component<Props> {
    constructor(props, context) {
        super(props, context);
        this.state = {
            isLoading: true,
            logs: []
        };
    }

    componentWillMount() {
        const { handleFlags, handleFlagsError } = this;
        bulletTrain.init({
            environmentID,
            onChange: handleFlags,
            onError: handleFlagsError,
            defaultFlags: {
                default_feature: true,
                font_size: 12,
            }
        });
        bulletTrain.startListening(2000)

    }

    logout = () => {
        bulletTrain.logout();
        this.forceUpdate();
    };

    submitTrait = () => {
        bulletTrain.setTrait('example_trait', !bulletTrain.getTrait('example_trait'));
    }

    login = () => {
        bulletTrain.identify("bullet_train_sample_user");
        this.forceUpdate();
    };

    render() {

        const trait = bulletTrain.getTrait("example_trait") + "";
        const fontSize = parseInt(bulletTrain.getValue("font_size"));
        const { isLoading, logs } = this.state;
        const { submitTrait } = this;
        return isLoading ? <Text>Loading</Text> : (
            <View style={{ padding: 50 }}>
                <Text style={{ fontSize }}>
                    {JSON.stringify(bulletTrain.flags)}
                </Text>
                {bulletTrain.identity ? (
                    <View>
                        <Button title={"logout"} onPress={this.logout}/>
                        <Button title={'Toggle user trait'} onPress={submitTrait}/>
                        <View>
                            <Text>
                                example_trait: {trait}
                            </Text>
                        </View>
                    </View>
                ) : <Button title={"login as sample user"} onPress={this.login}/>}
                <Text style={styles.title}>
                    Events
                </Text>
                {logs.map(({ timestamp, data, params, oldData }, i) => (
                    <Text key={i}>
                        {timestamp}: {data} {params} {oldData}
                    </Text>
                ))}
            </View>
        );
    }

    handleFlags = (oldFlags, params) => {
        this.setState({
            ...params,
            isLoading: false,
            logs: [{
                timestamp: new Date().toDateString(),
                params: JSON.stringify(params),
                oldData: JSON.stringify(oldFlags),
                data: JSON.stringify(bulletTrain.getAllFlags())
            }].concat(this.state.logs)
        });
    };
    handleFlagsError = (data) => {

    };

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    title: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
});

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import bulletTrain from 'bullet-train-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  logs = [];
  loading = true;
  environmentID = 'uCDQzKWgejrutqSYYsKWen';
  identity = null;
  buttonClicks = null;
  trait = null;

  constructor() {
    const { environmentID, handleFlags, handleFlagsError } = this;
    bulletTrain.init({
      environmentID,
      onChange: handleFlags,
      onError: handleFlagsError,
      defaultFlags: {
        default_feature: true,
        font_size: 12,
      }
    });
  }

  handleFlags = (oldFlags, params) => {
    this.loading = false;
    this.logs = [{
      timestamp: new Date().toTimeString(),
      params: JSON.stringify(params),
      data: JSON.stringify(bulletTrain.getAllFlags(), null, 2),
    }].concat(this.logs)
    this.identity = bulletTrain.identity;
    this.buttonClicks = bulletTrain.getTrait("button_clicks");
    this.trait = bulletTrain.getTrait("example_trait") + "";

  };

  handleFlagsError = (data) => {

  };

  logout = () => {
    bulletTrain.logout();
  };

  login = () => {
    bulletTrain.identify('bullet_train_sample_user');
  };

  submitTrait = () => {
    bulletTrain.setTrait('example_trait', 'Some value ' + Math.floor(Math.random() * 10) + '');
  }

  increment = (value) => {
    bulletTrain.incrementTrait('button_clicks', value)
  };

}

<!-- Toolbar -->

<div class="content" role="main">
  <h2>{{environmentID}}</h2>
  <div *ngIf="identity">
    <div>
      Button Clicks: {{buttonClicks}}
      <button (click)="increment(-1)">
      Decrement trait
      </button>
      <button (click)="increment(1)">
      Increment trait
      </button>
      <button (click)="submitTrait()">
        Toggle user trait
      </button>
      <div>
        example_trait: {{trait}}
      </div>
      <button (click)="logout()">
        logout
      </button>
    </div>
  </div>
  <div *ngIf="!identity">
    <button (click)="login()">
      Login as sample user
    </button>
  </div>
</div>
