// examples/angular-universal/src/app/app.component.ts
import { Component } from '@angular/core';
import { FlagsmithService } from './flagsmith.service';
import flagsmith from 'flagsmith/isomorphic'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private flagsmithService: FlagsmithService) {}

  setState = ()=> {
    this.fontSize = `${flagsmith.getValue("font_size")}`
    this.identity = !!flagsmith.identity;
    this.trait = flagsmith.getTrait("example_trait") + "";
    this.buttonClicks = parseInt(`${flagsmith.getTrait("button_clicks")}`);
  }

  ngOnInit() {
    this.flagsmithService.init(() => {
      this.setState()
    })
    this.setState()
  }

  logout = () => {
    flagsmith.logout();
  };

  login = () => {
    flagsmith.identify('flagsmith_sample_user');
  };

  submitTrait = () => {
    flagsmith.setTrait('example_trait', 'Some value ' + Math.floor(Math.random() * 10) + '');
  }

  buttonClicks = 0;
  fontSize = '';
  identity = false
  trait = ''
}


<div class="content" role="main">
  Font Size: {{fontSize}}
  <div *ngIf="identity">
    <div>
      Button Clicks: {{buttonClicks}}
      <button (click)="submitTrait()">
        Toggle user trait
      </button>
      <div>
        example_trait: {{trait}}
      </div>
      <button (click)="logout()">
        logout
      </button>
    </div>
  </div>
  <div *ngIf="!identity">
    <button (click)="login()">
      Login as sample user
    </button>
  </div>
</div>

// examples/svelte/src/lib/App.svelte
<script lang="ts">
	import { browser } from '$app/env';

	const updateFeatures = ()=> {
		fontSize = flagsmith.getValue("font_size");
		loggedIn = !!flagsmith.identity;
	}

	import flagsmith from "flagsmith/isomorphic"
	export let flagsmithState;
	if (browser && !flagsmith.initialised) {
		console.log("Initialising clientside Flagsmith with server state", flagsmithState)
		flagsmith.init({
			environmentID: "QjgYur4LQTwe5HpvbvhpzK",
			state: flagsmithState,
		})
	}

	let loggedIn = !!flagsmith.identity;
	let fontSize = flagsmith.getValue("font_size");

	function login () {
		flagsmith.identify("flagsmith_sample_user")
			.then(updateFeatures)
	};

	function logout () {
		flagsmith.logout().then(updateFeatures)
	};
</script>

<div class="counter">
	<div>
		Font Size: <strong class="hidden" aria-hidden="true">{
		fontSize
	}</strong>
	</div>
	{#if !loggedIn}
		<button on:click={login}>
			Log in
		</button>
	{/if}
	{#if loggedIn}
		<div>
			Example Trait: <strong className='hidden' aria-hidden='true'>{
			flagsmith.getTrait("example_trait")
		}</strong>
		</div>
		<button on:click={logout}>
			Logout
		</button>
	{/if}

</div>
